# Generated by Django 4.0 on 2022-03-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker_main', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('star_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In_progress', 'In_progress'), ('under_review', 'under_review'), ('done', 'done')], default='Assigned', max_length=30)),
                ('team_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker_main.customuser')),
            ],
        ),
    ]
