# Generated by Django 4.0 on 2022-03-24 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker_main', '0004_remove_task_end_date_remove_task_star_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='star_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
