# Generated by Django 4.0 on 2022-03-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker_main', '0005_task_end_date_task_star_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
