# Generated by Django 4.0 on 2022-03-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker_main', '0006_alter_task_task_name_alter_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='team_members',
            new_name='team_member_id',
        ),
    ]
