# Generated by Django 4.0 on 2022-03-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker_main', '0007_rename_team_members_task_team_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='team_member_id',
            new_name='team_members',
        ),
    ]
